# Generated by Django 4.2.24 on 2025-12-04 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Porcentaje entre 1 y 100', verbose_name='Porcentaje de Descuento')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 para ilimitado', verbose_name='Límite de Uso')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote / Grupo')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Template')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto del Correo (Default)')),
                ('content_html', models.TextField(blank=True, verbose_name='Contenido HTML')),
                ('design_json', models.JSONField(blank=True, null=True, verbose_name='Diseño (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketingtemplate',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='Descuento Aplicado')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('En camino', 'En camino'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Fallido', 'Fallido'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Estado')),
                ('channel', models.CharField(choices=[('Online', 'Online'), ('Tienda', 'Tienda')], default='Online', max_length=10, verbose_name='Canal')),
                ('delivery_method', models.CharField(default='Despacho', max_length=20, verbose_name='Método de Entrega')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre Destinatario')),
                ('shipping_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('shipping_commune', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('shipping_region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='appCommercefy.customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrado')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PointReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Canje')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('points_cost', models.PositiveIntegerField(verbose_name='Costo en Puntos')),
                ('reward_type', models.CharField(choices=[('COUPON', 'Cupón de Descuento'), ('PRODUCT', 'Producto Gratis')], default='PRODUCT', max_length=20, verbose_name='Tipo de Recompensa')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='URL Imagen (Opcional)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('coupon_batch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote de Cupones')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCommercefy.coupon', verbose_name='Cupón Asociado')),
            ],
            options={
                'verbose_name': 'Recompensa por Puntos',
                'verbose_name_plural': 'Recompensas por Puntos',
                'db_table': 'pointreward',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('price', models.PositiveIntegerField(help_text='Precio en CLP (entero)', verbose_name='Precio')),
                ('image_url', models.CharField(max_length=300, verbose_name='URL Imagen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('has_sizes', models.BooleanField(default=False, verbose_name='Tiene Tallas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='appCommercefy.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos Acumulados')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'userprofile',
            },
        ),
        migrations.CreateModel(
            name='RedemptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Puntos Gastados')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Canje')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCommercefy.pointreward', verbose_name='Recompensa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Canje',
                'verbose_name_plural': 'Historial de Canjes',
                'db_table': 'redemptionhistory',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='Especificación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='appCommercefy.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Especificación de Producto',
                'verbose_name_plural': 'Especificaciones de Productos',
                'db_table': 'productspec',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='Calificación')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Calificaciones')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Color')),
                ('descuento_pct', models.PositiveIntegerField(default=0, verbose_name='Porcentaje Descuento')),
                ('envio', models.CharField(blank=True, max_length=120, verbose_name='Envío')),
                ('llega', models.CharField(blank=True, max_length=120, verbose_name='Llega')),
                ('warranty', models.CharField(blank=True, max_length=120, verbose_name='Garantía')),
                ('capacity_l', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad (L)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='appCommercefy.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Producto',
                'verbose_name_plural': 'Detalles de Productos',
                'db_table': 'productdetail',
            },
        ),
        migrations.CreateModel(
            name='ProductCare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='Cuidado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care', to='appCommercefy.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Cuidado de Producto',
                'verbose_name_plural': 'Cuidados de Productos',
                'db_table': 'productcare',
            },
        ),
        migrations.CreateModel(
            name='ProductBreadcrumb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Posición')),
                ('label', models.CharField(max_length=60, verbose_name='Etiqueta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='appCommercefy.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Miga de Pan',
                'verbose_name_plural': 'Migas de Pan',
                'db_table': 'productbreadcrumb',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='pointreward',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCommercefy.product', verbose_name='Producto a Canjear'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(help_text='Precio unitario en CLP', verbose_name='Precio Unitario')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Talla')),
                ('is_reward', models.BooleanField(default=False, verbose_name='Es Recompensa')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appCommercefy.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='appCommercefy.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedidos',
                'db_table': 'orderitem',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Campaña')),
                ('subject', models.CharField(blank=True, help_text='Si se deja vacío usa el del template', max_length=200)),
                ('include_coupon', models.BooleanField(default=False, verbose_name='¿Incluir Cupón Personalizado?')),
                ('coupon_discount_percent', models.IntegerField(blank=True, default=0, verbose_name='% Descuento')),
                ('coupon_valid_days', models.IntegerField(default=7, verbose_name='Días de validez')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sent', 'Enviada')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appCommercefy.marketingtemplate')),
            ],
            options={
                'db_table': 'marketingcampaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCommercefy.marketingcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaignlog',
            },
        ),
        migrations.CreateModel(
            name='BulkOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Oferta')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='Porcentaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('products', models.ManyToManyField(related_name='bulk_offers', to='appCommercefy.product', verbose_name='Productos Afectados')),
            ],
            options={
                'verbose_name': 'Oferta Masiva',
                'verbose_name_plural': 'Ofertas Masivas',
                'db_table': 'bulkoffer',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Adquisición')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='appCommercefy.coupon', verbose_name='Cupón')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cupón de Usuario',
                'verbose_name_plural': 'Cupones de Usuarios',
                'db_table': 'usercoupon',
                'unique_together': {('user', 'coupon')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20, verbose_name='Etiqueta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='appCommercefy.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Talla de Producto',
                'verbose_name_plural': 'Tallas de Productos',
                'db_table': 'productsize',
                'unique_together': {('product', 'label')},
            },
        ),
    ]
