# Generated by Django 4.2.24 on 2025-12-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCommercefy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Multitienda', max_length=100, verbose_name='Nombre del Sitio')),
                ('support_email', models.EmailField(default='contacto@multitienda.cl', max_length=254, verbose_name='Email de Soporte')),
                ('support_phone', models.CharField(default='+56 9 8837 6786', max_length=20, verbose_name='Teléfono de Soporte')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name='Logo del Sitio')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
