# Generated by Django 4.2.24 on 2025-12-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCommercefy', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto del Anuncio'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Breve descripción para buscadores', verbose_name='Descripción del Sitio (SEO)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#3b84f8', help_text='Formato HEX (ej: #3b84f8)', max_length=7, verbose_name='Color Primario'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#9df38b', help_text='Formato HEX (ej: #9df38b)', max_length=7, verbose_name='Color Secundario'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_announcement',
            field=models.BooleanField(default=False, verbose_name='Mostrar Anuncio'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter/X URL'),
        ),
    ]
