# Generated by Django 4.2.24 on 2025-12-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCommercefy', '0004_siteconfiguration_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='accent_color_dark',
            field=models.CharField(default='#FFC085', help_text='Formato HEX', max_length=7, verbose_name='Color de Acentos Oscuro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bg_body',
            field=models.CharField(default='#F8F9FA', help_text='Formato HEX', max_length=7, verbose_name='Fondo Body'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bg_soft',
            field=models.CharField(default='#F5F5F5', help_text='Formato HEX', max_length=7, verbose_name='Fondo Suave'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bg_surface',
            field=models.CharField(default='#FFFFFF', help_text='Formato HEX', max_length=7, verbose_name='Fondo Superficie'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='danger_color',
            field=models.CharField(default='#ed6464', help_text='Formato HEX', max_length=7, verbose_name='Color Peligro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='danger_color_dark',
            field=models.CharField(default='#f35050', help_text='Formato HEX', max_length=7, verbose_name='Color Peligro Oscuro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='info_color',
            field=models.CharField(default='#9BF6FF', help_text='Formato HEX', max_length=7, verbose_name='Color Información'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color_dark',
            field=models.CharField(default='#276adf', help_text='Formato HEX', max_length=7, verbose_name='Color Primario Oscuro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color_light',
            field=models.CharField(default='#5789e7', help_text='Formato HEX', max_length=7, verbose_name='Color Primario Claro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color_dark',
            field=models.CharField(default='#82e76c', help_text='Formato HEX', max_length=7, verbose_name='Color Secundario Oscuro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='success_color',
            field=models.CharField(default='#CAFFBF', help_text='Formato HEX', max_length=7, verbose_name='Color Éxito'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_light',
            field=models.CharField(default='#B2BEC3', help_text='Formato HEX', max_length=7, verbose_name='Texto Claro'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_main',
            field=models.CharField(default='#2D3436', help_text='Formato HEX', max_length=7, verbose_name='Texto Principal'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_muted',
            field=models.CharField(default='#636E72', help_text='Formato HEX', max_length=7, verbose_name='Texto Silenciado'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='warning_color',
            field=models.CharField(default='#FFD93D', help_text='Formato HEX', max_length=7, verbose_name='Color Advertencia'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='accent_color',
            field=models.CharField(default='#FFD6A5', help_text='Formato HEX', max_length=7, verbose_name='Color de Acentos'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_color',
            field=models.CharField(default='#1a1a1a', help_text='Formato HEX (ej: #1a1a1a)', max_length=7, verbose_name='Color de Texto Legado'),
        ),
    ]
