# Generated by Django 4.2.24 on 2025-12-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCommercefy', '0005_siteconfiguration_accent_color_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='product_card_bg',
            field=models.CharField(default='#FFFFFF', help_text='Formato HEX', max_length=7, verbose_name='Fondo Tarjeta Producto'),
        ),
    ]
