# Generated by Django 4.2.24 on 2025-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCommercefy', '0006_siteconfiguration_product_card_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
