# Generated by Django 4.2.26 on 2025-12-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCommercefy', '0007_siteconfiguration_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='pagina1', max_length=50, verbose_name='Nombre de la Página')),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section'), ('offers_carousel', 'Carrusel de Ofertas'), ('product_list', 'Lista de Productos'), ('info_cards', 'Tarjetas de Información'), ('html', 'HTML Personalizado')], max_length=50, verbose_name='Tipo de Bloque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Contenido (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Bloque de Página',
                'verbose_name_plural': 'Bloques de Página',
                'db_table': 'pageblock',
                'ordering': ['order'],
            },
        ),
    ]
